version: '3.8'

services:
  scooter-server-1:
    image: scooter-server:0.2
    networks:
      - scooter-net

  scooter-server-2:
    image: scooter-server:0.2
    networks:
      - scooter-net

  scooter-server-3:
    image: scooter-server:0.2
    networks:
      - scooter-net

  scooter-server-4:
    image: scooter-server:0.2
    networks:
      - scooter-net

  nginx:
    image: nginx:latest
    ports:
      - "50051:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - scooter-net
    depends_on:
      - scooter-server-1
      - scooter-server-2
      - scooter-server-3
      - scooter-server-4

networks:
  scooter-net:
    driver: bridge
