apiVersion: apps/v1
kind: Deployment
metadata:
  name: scooter-server
  labels:
    app: scooter-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scooter-server
  template:
    metadata:
      labels:
        app: scooter-server
    spec:
      containers:
        - name: scooter-server
          image: scooter-server:0.3
          env:
            - name: ETCD_SERVER
              value: "etcd:2379"
            - name: ETCD_LEASE_DURATION
              value: "60"  # Replace with actual value
            - name: PAXOS_PORT
              value: "50052"  # Replace with actual value
            - name: SNAPSHOT_INTERVAL
              value: "3600"  # Replace with actual value
          ports:
            - containerPort: 50052
---


apiVersion: v1
kind: Service
metadata:
  name: scooter-server
  labels:
    app: scooter-server
spec:
  ports:
    - port: 50053
      targetPort: 50053
  selector:
    app: scooter-server