apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  labels:
    app: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: scooter-spa:0.1
          ports:
            - containerPort: 80



---



apiVersion: v1
kind: Service
metadata:
  name: spa
  labels:
    app: spa
spec:
  ports:
    - port: 4300
      targetPort: 80
  selector:
    app: spa