// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: scooter.proto

package scooter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScooterService_GetScooterStatus_FullMethodName = "/scooter.ScooterService/GetScooterStatus"
)

// ScooterServiceClient is the client API for ScooterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScooterServiceClient interface {
	GetScooterStatus(ctx context.Context, in *ScooterRequest, opts ...grpc.CallOption) (*ScooterResponse, error)
}

type scooterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScooterServiceClient(cc grpc.ClientConnInterface) ScooterServiceClient {
	return &scooterServiceClient{cc}
}

func (c *scooterServiceClient) GetScooterStatus(ctx context.Context, in *ScooterRequest, opts ...grpc.CallOption) (*ScooterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScooterResponse)
	err := c.cc.Invoke(ctx, ScooterService_GetScooterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScooterServiceServer is the server API for ScooterService service.
// All implementations must embed UnimplementedScooterServiceServer
// for forward compatibility.
type ScooterServiceServer interface {
	GetScooterStatus(context.Context, *ScooterRequest) (*ScooterResponse, error)
	mustEmbedUnimplementedScooterServiceServer()
}

// UnimplementedScooterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScooterServiceServer struct{}

func (UnimplementedScooterServiceServer) GetScooterStatus(context.Context, *ScooterRequest) (*ScooterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScooterStatus not implemented")
}
func (UnimplementedScooterServiceServer) mustEmbedUnimplementedScooterServiceServer() {}
func (UnimplementedScooterServiceServer) testEmbeddedByValue()                        {}

// UnsafeScooterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScooterServiceServer will
// result in compilation errors.
type UnsafeScooterServiceServer interface {
	mustEmbedUnimplementedScooterServiceServer()
}

func RegisterScooterServiceServer(s grpc.ServiceRegistrar, srv ScooterServiceServer) {
	// If the following call pancis, it indicates UnimplementedScooterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScooterService_ServiceDesc, srv)
}

func _ScooterService_GetScooterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScooterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScooterServiceServer).GetScooterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScooterService_GetScooterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScooterServiceServer).GetScooterStatus(ctx, req.(*ScooterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScooterService_ServiceDesc is the grpc.ServiceDesc for ScooterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScooterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scooter.ScooterService",
	HandlerType: (*ScooterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScooterStatus",
			Handler:    _ScooterService_GetScooterStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scooter.proto",
}
